parserOptions:
    sourceType: "module"
    ecmaVersion: 2020
plugins:
    - prettier
extends:
    - eslint:recommended
    - plugin:prettier/recommended
env:
    es6: true
    node: true
    browser: true
rules:
    prettier/prettier: error
    prettier/end-of-line: crlf
    arrow-body-style: off
    prefer-arrow-callback: off
    no-undef: off
