parserOptions:
  sourceType: "module"
  ecmaVersion: 2020
plugins:
  - prettier
extends:
  - eslint:recommended
  - plugin:prettier/recommended
env:
  es6: true
  node: true
  browser: true
rules:
  prettier/prettier: error
  no-undef: off
